### PR TITLE
Bump to version 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by Prnyself**

### CODE REVIEW

**Comment by Xuanwo** [comment]
2.0.0-rc.1 instead of 2.0.0

**Comment by Prnyself** [comment]
> 2.0.0-rc.1 instead of 2.0.0

changed

**Comment by Xuanwo** [comment]
Update all dependes and enable dependbot

**Comment by Xuanwo** [comment]
`qsctl cat qs://xxxx > xxxxx` hang

```
DEBU[2020-04-02T17:55:46+08:00] Started MD5SumFileTask {Offset: 0, Path: jdk-8u112-linux-x64.tar.gz, Size: 183212596, Storage: Storager qingstor {Name: xxxxxx, Location: pek3a, WorkDir: /}}
```

**Pull request merged**
